[2025-02-19T18:05:02.110+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T18:05:02.128+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: First_tag_example.first_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-19T18:05:02.135+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: First_tag_example.first_task scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-19T18:05:02.136+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-19T18:05:02.165+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2025-02-08 00:00:00+00:00
[2025-02-19T18:05:02.172+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'First_tag_example', 'first_task', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/first_dag_example.py', '--cfg-path', '/tmp/tmpgqn2yk7j']
[2025-02-19T18:05:02.170+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T18:05:02.181+0000] {standard_task_runner.py:72} INFO - Started process 264 to run task
[2025-02-19T18:05:02.179+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask first_task
[2025-02-19T18:05:02.292+0000] {task_command.py:467} INFO - Running <TaskInstance: First_tag_example.first_task scheduled__2025-02-08T00:00:00+00:00 [running]> on host 4c8bb8eb4736
[2025-02-19T18:05:02.429+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='goncalo' AIRFLOW_CTX_DAG_ID='First_tag_example' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-19T18:05:02.438+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-19T18:05:02.472+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-19T18:05:02.474+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello world!"']
[2025-02-19T18:05:02.487+0000] {subprocess.py:99} INFO - Output:
[2025-02-19T18:05:02.500+0000] {subprocess.py:106} INFO - Hello world!
[2025-02-19T18:05:02.503+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-19T18:05:02.562+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-19T18:05:02.563+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=First_tag_example, task_id=first_task, run_id=scheduled__2025-02-08T00:00:00+00:00, execution_date=20250208T000000, start_date=20250219T180502, end_date=20250219T180502
[2025-02-19T18:05:02.676+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-19T18:05:02.729+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T18:05:02.741+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
